import os
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from dotenv import load_dotenv

load_dotenv()

def audit_investment_thesis(ticker: str, thesis: str) -> str:
    """
    Acts as the Supervisor Agent, auditing the Portfolio Manager's thesis
    for common cognitive biases (FOMO, Confirmation Bias, Loss Aversion, Recency Bias)
    and ensuring logical consistency.
    """
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.1, google_api_key=os.getenv("GOOGLE_API_KEY"))
    
    template = """
    You are an expert Senior Financial Auditor and Cognitive Bias Evaluator.
    Your task is to audit the following Investment Thesis generated by a Portfolio Manager for {ticker}.
    
    === Investment Thesis ===
    {thesis}
    
    Please provide an audit report containing:
    1. **Bias Assessment**: Check for common cognitive biases (such as Fear of Missing Out (FOMO), Confirmation Bias, Loss Aversion, Recency Bias). Explain if they are present or not.
    2. **Logical Consistency Check**: Verify if the final BUY/SELL/HOLD decision matches the textual reasoning of the technical and fundamental reports.
    3. **Audited Checklist**: Provide a list of:
       - Fear of Missing Out (FOMO)
       - Confirmation Bias
       - Recency Bias (over-weighting recent short-term trends)
       - Loss Aversion
       (Mark each as "Clear ✅" or "Warning ⚠️" with a short description).
    4. **Final Audit Score**: A rating from 1 to 10 on the objectivity and reliability of the thesis.
    
    Keep the report professional, critical, and structured with markdown.
    """
    
    prompt = PromptTemplate(template=template, input_variables=["ticker", "thesis"])
    chain = prompt | llm
    
    try:
        response = chain.invoke({"ticker": ticker, "thesis": thesis})
        return response.content
    except Exception as e:
        return f"Error in Supervisor Audit: {e}"
